### ISSUE TITLE
TODO: Publish docs

### ISSUE THREAD

**Issue by tsirif** [Epistimio/orion#39]
Documentation should be revised and a website should be published containing at least the following pages:

- [x] API and code reference
- [x] Installation & deployment process
- [ ] Execution recipes and examples
- [ ] Configuration documentation
- [ ] List of available extensions of `BaseAlgorithm` available
- [ ] Writing an extension of `BaseAlgorithm` and publishing it as a Python distribution
- [ ] Coding standards
- [ ] Developing and contribution process
- [ ] Roadmap, changelog and list of contributors

Also, write *tox* scripts to automate building and distributing docs.
Roadmap, changelog and contributors should probably be in *root* repo's directory as `.rst` files.
Configure sphinx where needed. For example, use `sphinx.ext.intersphinx` to link with `numpy` and `scipy` docs.

**Comment by bouthilx** [comment]
@tsirif What's the status? :)

**Comment by bouthilx** [comment]
Since this issue is stalling a bit I would propose we break the work into clear different parts. The part 1. would be urgent to get done for beta testers. Having beta testers will help us write part 3 so that clean tutorials are ready when we make public release. Meanwhile, we can write part 2 for people who are soon going to jump in as developers. Part 4 can wait for 1, 2, 3 to be done.

### 1. Base doc

- [ ] API and code reference
- [ ]  Installation & deployment process

### 2. Doc for development

- [ ]  Coding standards
- [ ]  Developing and contribution process
- [ ]  Roadmap, changelog and list of contributors

### 3. Doc for user tutorials

- [ ]  Execution recipes and examples
- [ ]  Configuration documentation

### 4. Doc for algo contributor tutorials

- [ ]  List of available extensions of BaseAlgorithm available
- [ ]  Writing an extension of BaseAlgorithm and publishing it as a Python distribution

**Comment by tsirif** [comment]
Well (2) has been done partially, not as I have it in my mind though.

**Comment by bouthilx** [comment]
Now using trello for these tasks
